name: Portofolio Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "ragilbmtr@gmail.com"
          git config --global user.name "Ragil Bimantara"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn
          npm run deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        run: npm run deploy:ci