name: Portofolio Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_REPOSITORY: saktibimantara/portofolio

jobs:
  automation-test:
    runs-on: ubuntu-latest
    steps:
    test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: | 
          git remote set-url origin https://git:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  build:
    if: ${{ always() }}
    needs: [automation-test]
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "ryobimantara@gmail.com"
          git config --global user.name "Ragil Bimantara"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          git remote set-url origin https://git:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn
          npm install -g gh-pages --saved-dev
      - name: Deploy
        run: npm run deploy:ci