name: Portofolio Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_REPOSITORY: saktibimantara/portofolio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "ryobimantara@gmail.com"
          git config --global user.name "Ragil Bimantara"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn
          npm install -g gh-pages --saved-dev
          npm run deploy
      - name: Deploy
        run: npm run deploy:ci